In [1]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv('data/horse_data.csv', \
    names = ['surgery', 'age', 'Hospital Number' \
             , 'rectal temperature', 'pulse', 'respiratory rate' \
             , 'temperature of extremities', 'peripheral pulse', 'mucous membranes', 'capillary refill time' \
             , 'pain ', 'peristalsis', 'abdominal distension', 'nasogastric tube', 'nasogastric reflux' \
             , 'nasogastric reflux PH', 'rectal examination - feces', 'abdomen', 'packed cell volume' \
            , 'total protein', 'abdominocentesis appearance', 'abdomcentesis total protein', 'outcome' \
            , 'surgical lesion', 'type of lesion_1', 'type of lesion_2', 'type of lesion_3' \
            , 'cp_data'], sep = ',', header = 0, na_values = '?' )

# какие типы признаков в нашем датафрейме?
df.head(10)

,surgery,age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion_1,type of lesion_2,type of lesion_3,cp_data
0,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
1,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
2,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
3,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
4,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
5,1.0,1,526802,37.9,48.0,16.0,1.0,1.0,1.0,1.0,...,37.0,7.0,NaN,NaN,1.0,1,3124,0,0,2
6,1.0,1,529607,NaN,60.0,NaN,3.0,NaN,NaN,1.0,...,44.0,8.3,NaN,NaN,2.0,1,2208,0,0,2
7,2.0,1,530051,NaN,80.0,36.0,3.0,4.0,3.0,1.0,...,38.0,6.2,NaN,NaN,3.0,1,3205,0,0,2
8,2.0,9,5299629,38.3,90.0,NaN,1.0,NaN,1.0,1.0,...,40.0,6.2,1.0,2.2,1.0,2,0,0,0,1
9,1.0,1,528548,38.1,66.0,12.0,3.0,3.0,5.0,1.0,...,44.0,6.0,2.0,3.6,1.0,1,2124,0,0,1

In [44]:
# процент пропущенных значений

(df.isna().mean() * 100).round(2).sort_values(ascending=False)

nasogastric reflux PH          82.27
abdomcentesis total protein    65.89
abdominocentesis appearance    54.85
abdomen                        39.46
nasogastric reflux             35.12
nasogastric tube               34.45
rectal examination - feces     34.11
peripheral pulse               23.08
rectal temperature             20.07
respiratory rate               19.40
temperature of extremities     18.73
abdominal distension           18.73
pain                           18.39
mucous membranes               15.38
peristalsis                    14.72
total protein                  11.04
capillary refill time          10.70
packed cell volume              9.70
pulse                           8.03
surgery                         0.33
outcome                         0.33
type of lesion_3                0.00
surgical lesion                 0.00
type of lesion_1                0.00
type of lesion_2                0.00
Hospital Number                 0.00
age                             0.00
cp_data                         0.00
dtype: float64

In [65]:
?pd.value_counts

In [66]:
df['outcome'].value_counts(dropna=False)

1.0    178
2.0     76
3.0     44
NaN      1
Name: outcome, dtype: int64

surgery - хирургия (1 = Да, ему сделали операцию; 2 = Он лечился без хирургического вмешательства)
age - возраст 
Hospital Number - Номер больницы
rectal temperature
temperature of extremities - температура конечностей (1 = Нормальный; 2 = Тепло; 3 = cool / прохладно; 4 = Холод)
pulse
outcome - результат (1 = жил; 2 = умер; 3 = был подвергнут эвтаназии)
surgical lesion - хирургическое повреждение (1.ретроспективно, была ли проблема (повреждение) хирургической; 2-все случаи либо прооперированы, либо вскрыты, так что)

In [51]:
print(df.shape)
df['outcome'].describe()

(299, 28)

count    298.000000
mean       1.550336
std        0.737967
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        3.000000
Name: outcome, dtype: float64

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   surgery                      298 non-null    float64
 1   age                          299 non-null    int64
 2   Hospital Number              299 non-null    int64
 3   rectal temperature           239 non-null    float64
 4   pulse                        275 non-null    float64
 5   respiratory rate             241 non-null    float64
 6   temperature of extremities   243 non-null    float64
 7   peripheral pulse             230 non-null    float64
 8   mucous membranes             253 non-null    float64
 9   capillary refill time        267 non-null    float64
 10  pain                         244 non-null    float64
 11  peristalsis                  255 non-null    float64
 12  abdominal distension         243 non-null    float64
 13  nasogastric tube             196 non-null    float64
 14  nasogastric reflux           194 non-null    float64
 15  nasogastric reflux PH        53 non-null     float64
 16  rectal examination - feces   197 non-null    float64
 17  abdomen                      181 non-null    float64
 18  packed cell volume           270 non-null    float64
 19  total protein                266 non-null    float64
 20  abdominocentesis appearance  135 non-null    float64
 21  abdomcentesis total protein  102 non-null    float64
 22  outcome                      298 non-null    float64
 23  surgical lesion              299 non-null    int64
 24  type of lesion_1             299 non-null    int64
 25  type of lesion_2             299 non-null    int64
 26  type of lesion_3             299 non-null    int64
 27  cp_data                      299 non-null    int64
dtypes: float64(21), int64(7)
memory usage: 65.5 KB

In [62]:
print(df.groupby(['surgery', 'outcome']).count())

                 age  Hospital Number  rectal temperature  pulse  \
surgery outcome
1.0     1.0       95               95                  80     88
        2.0       58               58                  39     49
        3.0       27               27                  21     27
2.0     1.0       83               83                  72     78
        2.0       18               18                  13     16
        3.0       17               17                  13     16

                 respiratory rate  temperature of extremities  \
surgery outcome
1.0     1.0                    76                          75
        2.0                    45                          47
        3.0                    23                          18
2.0     1.0                    71                          71
        2.0                    12                          16
        3.0                    13                          15

                 peripheral pulse  mucous membranes  capillary refill time  \
surgery outcome
1.0     1.0                    75                78                     84
        2.0                    42                49                     50
        3.0                    17                21                     24
2.0     1.0                    64                72                     75
        2.0                    16                17                     16
        3.0                    15                15                     17

                 pain   ...  abdomen  packed cell volume  total protein  \
surgery outcome         ...
1.0     1.0         75  ...       58                  88             87
        2.0         48  ...       31                  51             49
        3.0         20  ...       19                  22             22
2.0     1.0         69  ...       47                  77             78
        2.0         16  ...       12                  17             15
        3.0         15  ...       13                  14             14

                 abdominocentesis appearance  abdomcentesis total protein  \
surgery outcome
1.0     1.0                               48                           32
        2.0                               31                           20
        3.0                               15                           17
2.0     1.0                               26                           20
        2.0                                5                            4
        3.0                                9                            8

                 surgical lesion  type of lesion_1  type of lesion_2  \
surgery outcome
1.0     1.0                   95                95                95
        2.0                   58                58                58
        3.0                   27                27                27
2.0     1.0                   83                83                83
        2.0                   18                18                18
        3.0                   17                17                17

                 type of lesion_3  cp_data
surgery outcome
1.0     1.0                    95       95
        2.0                    58       58
        3.0                    27       27
2.0     1.0                    83       83
        2.0                    18       18
        3.0                    17       17

[6 rows x 26 columns]

# Задание 2. Работа с выбросами

В выбранных числовых столбцах найти выбросы, выдвинуть гипотезы об их причинах и проинтерпретировать результаты. Принять и обосновать решение о дальнейшей работе с ними.1